In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from sklearn.cluster import KMeans

In [3]:
df = pd.read_csv('nba_df.csv')

In [4]:
df

year          Player Pos  Age   Tm   G  GS    MP   FG  FGA  ...  ORB  \
0     2015  Jarnell Stokes   C   22  MEM   2   0     4    0    0  ...    1   
1     2015    Jordan McRae  PG   24  TOT  22   1   195   34   78  ...    4   
2     2015  Mario Chalmers  PG   29  MIA   6   0   120   10   32  ...    1   
3     2015   Marcus Morris  SF   26  DET  80  80  2856  410  945  ...   91   
4     2015  Draymond Green  PF   25  GSW  81  81  2808  401  819  ...  134   
...    ...             ...  ..  ...  ...  ..  ..   ...  ...  ...  ...  ...   
3164  2019      Alec Burks  SG   28  PHI  11   0   222   39  100  ...    6   
3165  2019        Rudy Gay  PF   33  SAS  60   5  1287  222  502  ...   56   
3166  2019     Jae Crowder  SF   29  MIA  13   1   373   50  114  ...    8   
3167  2019     Matt Mooney  SG   22  CLE   4   0    19    1    4  ...    0   
3168  2019      Dante Exum  SG   24  CLE  24   1   402   46   96  ...    9   

      DRB  TRB  AST  STL  BLK  TOV   PF   PTS  All_Star  
0       1    2    0    0    0    0    0     0         0  
1      16   20   25    3    1   15   17    99         0  
2      13   14   19    8    1    9   16    33         0  
3     313  404  201   67   23  140  170  1131         0  
4     635  769  598  119  113  259  240  1131         1  
...   ...  ...  ...  ...  ...  ...  ...   ...       ...  
3164   30   36   20    8    0    9   13   118         0  
3165  266  322  101   26   28   78   89   601         0  
3166   68   76   26   20    7    8   41   155         0  
3167    3    3    1    2    1    0    1     2         0  
3168   46   55   33   12    6   21   30   135         0  

[3169 rows x 31 columns]

In [130]:
nba.loc[:, ].mean()

year       2014.000000
age          26.637755
g            53.971939
gs           26.436224
mp         1252.604592
fg          195.466837
fga         428.732143
fgx           0.437335
3p           40.311224
3pa         111.308673
3px           0.284210
2p          155.155612
2pa         317.423469
2px           0.467579
efgx          0.482169
ft           92.910714
fta         122.538265
ftx           0.728232
orb          56.795918
drb         166.783163
trb         223.579082
ast         113.829082
stl          39.964286
blk          25.140306
tov          72.431122
pf          107.107143
pts         524.155612
allstar       0.058673
dtype: float64

In [5]:
kmeans_model = KMeans(n_clusters=5, random_state=1)
clean_model = df._get_numeric_data().dropna(axis=1)
kmeans_model.fit(clean_model)
name = kmeans_model.labels_
name.dtype

dtype('int32')

In [8]:
df['cluster'] = name

df.head(44)

year              Player Pos  Age   Tm   G  GS    MP   FG   FGA  ...  DRB  \
0   2015      Jarnell Stokes   C   22  MEM   2   0     4    0     0  ...    1   
1   2015        Jordan McRae  PG   24  TOT  22   1   195   34    78  ...   16   
2   2015      Mario Chalmers  PG   29  MIA   6   0   120   10    32  ...   13   
3   2015       Marcus Morris  SF   26  DET  80  80  2856  410   945  ...  313   
4   2015      Draymond Green  PF   25  GSW  81  81  2808  401   819  ...  635   
5   2015        DeJuan Blair   C   26  WAS  29   0   218   28    68  ...   37   
6   2015      Christian Wood  PF   20  PHI  17   0   145   22    53  ...   25   
7   2015        Bryce Cotton  PG   23  TOT   8   0    39    4    10  ...    0   
8   2015       Briante Weber  PG   23  TOT   7   4   169   14    39  ...   17   
9   2015           Ty Lawson  PG   28  IND  13   1   235   28    67  ...   25   
10  2015    DeMarcus Cousins   C   25  SAC  65  65  2246  601  1332  ...  589   
11  2015         C.J. Wilcox  SG   25  LAC  23   0   167   26    66  ...   11   
12  2015        J.J. Hickson   C   27  WAS  15   0   131   25    46  ...   28   
13  2015        Derrick Rose  PG   27  CHI  66  66  2097  447  1048  ...  179   
14  2015        Kirk Hinrich  PG   35  ATL  11   0    76    2    11  ...   11   
15  2015        Devyn Marble  SG   23  ORL  28   0   249   21    71  ...   32   
16  2015       Briante Weber  PG   23  MEM   6   4   166   13    38  ...   16   
17  2015        Jordan McRae  PG   24  CLE  15   1   113   23    52  ...   10   
18  2015       Ryan Anderson  PF   27  NOP  66   7  2008  397   929  ...  265   
19  2015     Jimmer Fredette  SG   26  NYK   2   0     5    1     1  ...    0   
20  2015        Caron Butler  SF   35  SAC  17   1   176   25    59  ...   17   
21  2015        Jarell Eddie  SF   24  WAS  26   0   147   20    65  ...   21   
22  2015        Jordan Adams  SG   21  MEM   2   0    15    2     6  ...    2   
23  2015      Justin Holiday  SG   26  ATL  26   1   263   24    73  ...   23   
24  2015         Mike Miller  SF   35  DEN  47   2   373   22    62  ...   47   
25  2015        Ryan Hollins   C   31  WAS   5   3    48    4     7  ...    4   
26  2015    Cleanthony Early  SF   24  NYK  17   2   154   12    40  ...   22   
27  2015     Elliot Williams  PG   26  MEM   5   0    45    2    10  ...    3   
28  2015      Jamal Crawford  SG   35  LAC  79   5  2126  379   939  ...  125   
29  2015       Eric Moreland  PF   24  SAC   8   0    48    3     6  ...    8   
30  2015       Nazr Mohammed   C   38  OKC   5   0    19    3     5  ...    3   
31  2015       Anthony Davis   C   22  NOP  61  61  2164  560  1136  ...  497   
32  2015         Monta Ellis  SG   30  IND  81  81  2734  436  1021  ...  229   
33  2015       Tobias Harris  PF   23  TOT  76  74  2513  417   889  ...  414   
34  2015         Steve Novak  PF   32  MIL   3   0    20    2     6  ...    1   
35  2015      Branden Dawson  PF   22  LAC   6   0    29    2     5  ...    2   
36  2015          Duje Dukan  SF   24  SAC   1   0    24    2    10  ...    2   
37  2015       Brian Roberts  PG   30  POR  21   0   137   23    50  ...   10   
38  2015      Jason Thompson   C   29  GSW  28   1   179   20    42  ...   44   
39  2015        Kemba Walker  PG   25  CHO  81  81  2885  568  1331  ...  301   
40  2015      Nikola Peković   C   30  MIN  12   3   156   19    50  ...   14   
41  2015  Shayne Whittington  PF   24  IND   7   0    41    5    11  ...    7   
42  2015       Kawhi Leonard  SF   24  SAS  72  72  2380  551  1090  ...  398   
43  2015      Jarnell Stokes   C   22  TOT   7   0    18    3     5  ...    3   

    TRB  AST  STL  BLK  TOV   PF   PTS  All_Star  cluster  
0     2    0    0    0    0    0     0         0        0  
1    20   25    3    1   15   17    99         0        0  
2    14   19    8    1    9   16    33         0        0  
3   404  201   67   23  140  170  1131         0        1  
4   769  598  119  113  259  240  1131         1        1 

In [9]:
df.to_csv('tableau_df.csv', index=False)

In [134]:
Robert_Sacre = clean_model.loc[nba['player'] == 'Robert Sacre',: ]
Robert_Sacre

year  age   g  gs    mp   fg  fga  3p  3pa   2p  ...  orb  drb  trb  ast  \
323  2014   24  65  13  1089  143  300   0    0  143  ...   82  172  254   51   

     stl  blk  tov   pf  pts  allstar  
323   24   47   44  134  350        0  

[1 rows x 23 columns]

In [135]:
Robert_Sacre_cluster = Robert_Sacre.values.tolist()
kmeans_model.predict(Robert_Sacre_cluster)

array([4])

In [136]:
Andrew_Bynum = clean_model.loc[nba['player'] == 'Andrew Bynum',: ]
Andrew_Bynum
Andrew_Bynum_cluster = Andrew_Bynum.values.tolist()
kmeans_model.predict(Andrew_Bynum_cluster)

array([1])

In [137]:
LeBron_James = clean_model.loc[nba['player'] == 'LeBron James',: ]
LeBron_James

year  age   g  gs    mp   fg   fga   3p  3pa   2p  ...  orb  drb  trb  \
250  2014   29  77  77  2902  767  1353  116  306  651  ...   81  452  533   

     ast  stl  blk  tov   pf   pts  allstar  
250  488  121   26  270  126  2089        1  

[1 rows x 23 columns]

In [138]:
LeBron_James_cluster = LeBron_James.values.tolist()
kmeans_model.predict(LeBron_James_cluster)

array([3])

In [139]:
Kevin_Durant = clean_model.loc[nba['player'] == 'Kevin Durant',: ]
Kevin_Durant

year  age   g  gs    mp   fg   fga   3p  3pa   2p  ...  orb  drb  trb  \
232  2014   25  81  81  3122  849  1688  192  491  657  ...   58  540  598   

     ast  stl  blk  tov   pf   pts  allstar  
232  445  103   59  285  174  2593        1  

[1 rows x 23 columns]

In [140]:
Kevin_Durant_cluster = Kevin_Durant.values.tolist()
kmeans_model.predict(Kevin_Durant_cluster)

array([3])

In [141]:
Tim_Duncan = clean_model.loc[nba['player'] == 'Tim Duncan',: ]
Tim_Duncan

year  age   g  gs    mp   fg  fga  3p  3pa   2p  ...  orb  drb  trb  ast  \
359  2014   37  74  74  2158  444  906   0    5  444  ...  158  563  721  220   

     stl  blk  tov   pf   pts  allstar  
359   43  139  159  134  1119        0  

[1 rows x 23 columns]

In [142]:
Tim_Duncan_cluster = Tim_Duncan.values.tolist()
kmeans_model.predict(Tim_Duncan_cluster)

array([2])

In [143]:
Kawhi_Leonard = clean_model.loc[nba['player'] == 'Kawhi Leonard',: ]
Kawhi_Leonard

year  age   g  gs    mp   fg  fga  3p  3pa   2p  ...  orb  drb  trb  ast  \
224  2014   22  66  65  1923  337  645  69  182  268  ...   76  336  412  133   

     stl  blk  tov   pf  pts  allstar  
224  114   50   80  127  844        0  

[1 rows x 23 columns]

In [144]:
Kawhi_Leonard_cluster = Kawhi_Leonard.values.tolist()
kmeans_model.predict(Kawhi_Leonard_cluster)

array([0])

In [145]:
Carmelo_Anthony = clean_model.loc[nba['player'] == 'Carmelo Anthony',: ]
Carmelo_Anthony

year  age   g  gs    mp   fg   fga   3p  3pa   2p  ...  orb  drb  trb  \
102  2014   29  77  77  2982  743  1643  167  415  576  ...  145  477  622   

     ast  stl  blk  tov   pf   pts  allstar  
102  242   95   51  198  224  2112        1  

[1 rows x 23 columns]

In [146]:
Carmelo_Anthony_cluster = Carmelo_Anthony.values.tolist()
kmeans_model.predict(Carmelo_Anthony_cluster)

array([3])

In [149]:
Stephen_Curry = clean_model.loc[nba['player'] == 'Stephen Curry',: ]
Stephen_Curry

year  age   g  gs    mp   fg   fga   3p  3pa   2p  ...  orb  drb  trb  \
348  2014   25  78  78  2846  652  1383  261  615  391  ...   46  288  334   

     ast  stl  blk  tov   pf   pts  allstar  
348  666  128   14  294  194  1873        1  

[1 rows x 23 columns]

In [150]:
Stephen_Curry_cluster = Stephen_Curry.values.tolist()
kmeans_model.predict(Stephen_Curry_cluster)

array([3])

In [151]:
Wesley_Matthews = clean_model.loc[nba['player'] == 'Wesley Matthews',: ]
Wesley_Matthews

year  age   g  gs    mp   fg   fga   3p  3pa   2p  ...  orb  drb  trb  \
384  2014   27  82  82  2780  445  1009  201  511  244  ...   51  238  289   

     ast  stl  blk  tov   pf   pts  allstar  
384  197   76   14  110  176  1343        0  

[1 rows x 23 columns]

In [152]:
Wesley_Matthews_cluster = Wesley_Matthews.values.tolist()
kmeans_model.predict(Wesley_Matthews_cluster)

array([2])